/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_diastrofunk_rabbitmqtest_NDKTests */

#ifndef _Included_com_diastrofunk_rabbitmqtest_NDKTests
#define _Included_com_diastrofunk_rabbitmqtest_NDKTests
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_diastrofunk_rabbitmqtest_NDKTests
 * Method:    connect
 * Signature: (Ljava/lang/String;ILjava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_diastrofunk_rabbitmqtest_NDKTests_connect
  (JNIEnv *, jobject, jstring, jint, jstring, jstring, jstring);

/*
 * Class:     com_diastrofunk_rabbitmqtest_NDKTests
 * Method:    disconnect
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_diastrofunk_rabbitmqtest_NDKTests_disconnect
  (JNIEnv *, jobject);

/*
 * Class:     com_diastrofunk_rabbitmqtest_NDKTests
 * Method:    createchannel
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_diastrofunk_rabbitmqtest_NDKTests_createchannel
  (JNIEnv *, jobject);

/*
 * Class:     com_diastrofunk_rabbitmqtest_NDKTests
 * Method:    basicconsume
 * Signature: (ILjava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_diastrofunk_rabbitmqtest_NDKTests_basicconsume
  (JNIEnv *, jobject, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
